name: deps-sync
on:
  schedule:
    - cron: 0 3 * * *
  push:
    branches:
      - main
      - deps
      - deps-sync
      - 'deps-sync/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - id: branches
        name: Set branch variables
        run: |
          echo head=deps >> $GITHUB_OUTPUT
          echo base=main >> $GITHUB_OUTPUT
      - id: checkout_deps
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: deps
      - name: Configure git # needed to author commits
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Merge latest ${{ steps.branches.outputs.base }}
        run: |
          git fetch
          git merge --strategy-option theirs origin/${{ steps.branches.outputs.base }}
      - name: Update lockfile
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile
      - name: Commit lockfile changes
        id: commit_changes
        run: |
          git status
          GIT_STATUS=$(git status --porcelain)
          if [ -z "$GIT_STATUS" ]; then
            echo "no working changes, nothing to commit"
          else
            echo changes=yes >> $GITHUB_OUTPUT
            git add .
            git commit -m 'chore: changes after pnpm install' --no-verify
          fi
      - name: Push changes
        id: push_changes
        run: |
          is_ahead=$(git status | grep 'Your branch is ahead' || echo '')
          if [ -z "$is_ahead" ]; then
            git status
            echo "no changes to push"
          else
            echo ahead=yes >> $GITHUB_OUTPUT
            git push
          fi
      - name: Create pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const iterator = github.paginate.iterator(github.rest.pulls.list, {
              ...context.repo,
              state: 'open',
            })
            const head = '${{ steps.branches.outputs.haed }}'
            const base = '${{ steps.branches.outputs.base }}'

            const getBranch = async branch => {
              const {data} = await github.rest.repos.getBranch({...context.repo, branch})
              return data
            }

            const {commit: latestHead} = await getBranch(head)
            const {commit: latestBase} = await getBranch(base)

            console.log(`Head: ${head}, sha: ${latestHead.sha}, parents: ${latestHead.parents.map(p => p.sha).join(', ')}`)
            console.log(`Base: ${base}, sha: ${latestBase.sha}, parents: ${latestBase.parents.map(p => p.sha).join(', ')}`)

            const {data: comparison} = await github.rest.repos.compareCommits({
              ...context.repo,
              base: latestBase.sha,
              head: latestHead.sha
            })

            if (comparison.status === 'identical') {
              console.log(`No changes between ${head} and ${base}. ${head} is identical to ${base}: ${latestHead.commit?.message}`)
              return
            }

            if (comparison.status === 'ahead' && latestHead.parents.some(parent => parent.sha === latestBase.sha)) {
              console.log(`No changes between ${head} and ${base}. ${head} is a descendant of ${base}: ${latestHead.commit?.message}`)
              return
            }

            for await (const {data: pulls} of iterator) {
              const existing = pulls.find(p => p.head.ref === head && p.base.ref === base)
              if (existing) {
                console.log(`Pull request into ${base} from ${head} already exists: ${existing.title} ${existing.html_url}`)
                return
              }
            }

            await github.rest.pulls.create({
              ...context.repo,
              head,
              base,
              title: 'chore: update dependencies',
              body: [
                'This PR was automatically created by the ${{ github.workflow }} workflow.',
                '',
                `Renovate will continue to push to ${head}.`,
                '',
                'Review each dependency update and merge as needed.',
              ].join('\n'),
            })
